CREATE SCHEMA feature;

CREATE TABLE feature.feature (
    id uuid NOT NULL,
    name varchar(100) NOT NULL,
    CONSTRAINT pk_feature PRIMARY KEY (id),
    CONSTRAINT ck_feature_name_not_blank CHECK (btrim(name) <> '')
);

COMMENT ON SCHEMA feature IS 'Minimal starter feature';
COMMENT ON TABLE feature.feature IS 'Minimal feature record for starter verification';
COMMENT ON COLUMN feature.feature.id IS 'UUID v7 generated by the application';
COMMENT ON COLUMN feature.feature.name IS 'Non-blank display name, up to 100 characters';
