name: spring-application-starter
desc: Application database
docPath: build/documentation/database
er:
  format: mermaid
  hideDef: true
  showColumnTypes:
    related: true
  distance: 1
exclude:
  - public.flyway_schema_history
  - information_schema.*
  - pg_*.*
